### ISSUE TITLE
the result is different from opencv cpu

### ISSUE THREAD

**Issue by gitlabspy** [AlainPaillou/PyCuda_Denoise_Filters#3]
Thanks for your amazing works!
I found the result is different from ver. produced by opencv cpu. Is there a way to match up the params between gpu version and cpu version?  What is the meaning of `NLM_Noise`, `lerpC` and `nb_ThreadsY` and `nb_blocks`.

**Comment by AlainPaillou** [comment]
Hello,

it is possible the result is different between OpenCV and PyCuda GPU. As i don't know how fastNLM routines works with OpenCV, i can't explain the difference.

For the KNN noise removal program, it is also important to consider that i used FastNLM OpenCV routine because KNN noise removal routine does not exist with OpenCV. I know this is not really good but i have no OpenCV routine to compare with PyCuda routine.

NLM_Noise is used to set Noise parameter. lerpc is also a parameter used to set the NLM filter result. You can try to change those parameters ( abit lower, a bit higher) to see the result.

nb_threads and nb_blocks are used to define how CUDA cores will be used. Threads are related to GPU hardware and from what i now, nb_threadsX*nb_threadsY must be equal or inferior to 1024. You could set nb_threadsX to 32 and the same to nb_threadsY to make tests. But from what i know, it won't change many things.

Alain
